# Generated by Django 5.0.6 on 2025-12-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keitaro_id', models.IntegerField(unique=True, verbose_name='ID в Keitaro')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Алиас')),
                ('state', models.CharField(default='active', max_length=50, verbose_name='Состояние')),
                ('type', models.CharField(default='position', max_length=50, verbose_name='Тип')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Синхронизировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keitaro_id', models.IntegerField(verbose_name='ID в Keitaro')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция')),
                ('state', models.CharField(default='active', max_length=50, verbose_name='Состояние')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Синхронизировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
                'db_table': 'flows',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='FlowOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.IntegerField(default=0, help_text='Процент трафика (0-100)', verbose_name='Доля (%)')),
                ('is_pinned', models.BooleanField(default=False, help_text='Зафиксированный share не пересчитывается автоматически', verbose_name='Зафиксирован')),
                ('state', models.CharField(choices=[('active', 'Активен'), ('disabled', 'Отключен')], default='active', max_length=20, verbose_name='Состояние')),
                ('keitaro_offer_stream_id', models.IntegerField(blank=True, null=True, verbose_name='ID связи в Keitaro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Оффер в потоке',
                'verbose_name_plural': 'Офферы в потоках',
                'db_table': 'flow_offers',
                'ordering': ['flow', '-share'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keitaro_id', models.IntegerField(unique=True, verbose_name='ID в Keitaro')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('state', models.CharField(default='active', max_length=50, verbose_name='Состояние')),
                ('cached_at', models.DateTimeField(auto_now=True, verbose_name='Кэшировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
                'db_table': 'offers',
                'ordering': ['name'],
            },
        ),
    ]
