# Generated by Django 5.0.6 on 2025-12-13 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='flow',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='campaigns.campaign', verbose_name='Кампания'),
        ),
        migrations.AddField(
            model_name='flowoffer',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_offers', to='campaigns.flow', verbose_name='Поток'),
        ),
        migrations.AddField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='flowoffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_offers', to='campaigns.offer', verbose_name='Оффер'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['keitaro_id'], name='campaigns_keitaro_bfcc87_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['user', 'state'], name='campaigns_user_id_358125_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['campaign', 'state'], name='flows_campaig_026074_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['keitaro_id'], name='flows_keitaro_be532d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together={('campaign', 'keitaro_id')},
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['keitaro_id'], name='offers_keitaro_793cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['user', 'state'], name='offers_user_id_ab9c22_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['name'], name='offers_name_ae1882_idx'),
        ),
        migrations.AddIndex(
            model_name='flowoffer',
            index=models.Index(fields=['flow', 'state'], name='flow_offers_flow_id_6df4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='flowoffer',
            index=models.Index(fields=['keitaro_offer_stream_id'], name='flow_offers_keitaro_c37ffc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flowoffer',
            unique_together={('flow', 'offer')},
        ),
    ]
