# Generated by Django 5.1.4 on 2025-12-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaigns_user_id_358125_idx',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='user',
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['state'], name='campaigns_state_3fa02d_idx'),
        ),
    ]
