# Generated by Django 5.0.6 on 2025-12-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='type',
            field=models.CharField(default='offers', max_length=50, verbose_name='Тип потока'),
        ),
    ]
