# Generated by Django 5.1.4 on 2025-12-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Не используется для входа', max_length=150, null=True, verbose_name='Имя пользователя'),
        ),
    ]
